name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - GitHubActions/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: GitHubActions

      - name: Run tests
        run: node test.js
        working-directory: GitHubActions
